server:
  port: 8081
spring:
  application:
    name: service-hi
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: root
#      url: jdbc:mysql://192.168.186.100:3306/swldb?characterEncoding=utf-8&useSSL=false
      username: dtsf
      password: 1234yjd
      url: jdbc:mysql://133.96.6.1:3306/swldb?characterEncoding=utf-8&useSSL=false
      initial-size: 30
      min-idle: 30
      max-active: 100
      max-wait: 30000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 0
      validation-query: SELECT 1 FROM dual
      validation-query-timeout: 3
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 900000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      filters: stat,wall
      filter:
        slf4j:
          statement-executable-sql-log-enable: true
          enabled: true

#  redis:
#    cluster:
#      nodes:
#        - demo1:10001
#        - demo1:10003
#        - demo2:10001
#        - demo2:10003
#        - demo3:10001
#        - demo3:10003
#    password: 123456
#    pool:
#      min-idle: 2
#      max-idle: 5
#      max-active: 8
#      max-wait: 2000

