spring:
  profiles:
    active: common
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    prefix:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    enabled: true
#    settings:
#      template_update_delay: 0
appm:
  zkUrl: 133.96.6.1:2181,133.96.6.2:2181,133.96.6.3:2181