server:
  port: 7080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: service-zuul
zuul:
  routes:
    a:
      path: /a/**
      serviceId: consumer-hi
  retryable: true
ribbon:
  ConnectTimeout: 250
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000