server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: service-hi
  datasource:
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      username: scifmation
      password: kxht#123
      url: jdbc:oracle:thin:@133.96.9.118:7521:orcl